
const RESTAURANTS_LIST_FETCH_REQUEST = 'RESTAURANTS_LIST_FETCH_REQUEST';
const RESTAURANTS_LIST_FETCH_SUCCESS = 'RESTAURANTS_LIST_FETCH_SUCCESS';
const RESTAURANTS_LIST_FETCH_FAIL = 'RESTAURANTS_LIST_FETCH_FAIL';
const RESTAURANT_DETAILS_FETCH_REQUEST = 'RESTAURANT_DETAILS_FETCH_REQUEST';
const RESTAURANT_DETAILS_FETCH_SUCCESS = 'RESTAURANT_DETAILS_FETCH_SUCCESS';
const RESTAURANT_DETAILS_FETCH_FAIL = 'RESTAURANT_DETAILS_FETCH_FAIL';
const RESTAURANT_MENU_FETCH_REQUEST = 'RESTAURANT_MENU_FETCH_REQUEST';
const RESTAURANT_MENU_FETCH_SUCCESS = 'RESTAURANT_MENU_FETCH_SUCCESS';
const RESTAURANT_MENU_FETCH_FAIL = 'RESTAURANT_MENU_FETCH_FAIL';


export {
  RESTAURANTS_LIST_FETCH_REQUEST,
  RESTAURANTS_LIST_FETCH_SUCCESS,
  RESTAURANTS_LIST_FETCH_FAIL,
  RESTAURANT_DETAILS_FETCH_REQUEST,
  RESTAURANT_DETAILS_FETCH_SUCCESS,
  RESTAURANT_DETAILS_FETCH_FAIL,
  RESTAURANT_MENU_FETCH_REQUEST,
  RESTAURANT_MENU_FETCH_SUCCESS,
  RESTAURANT_MENU_FETCH_FAIL
};
